### ISSUE TITLE
Search by username do not work on dev env

### ISSUE THREAD

**Issue by autogestion** [jaywink/socialhome#406] opened 2018-01-19 14:43 UTC
ProfileIndex is set up to search by fields "name" and "handle". Field "name" remains empty after registration (and do not take part in search), and search by username from beginning of "handle" do not work

Locally, got 11 profiles
![11prof](https://user-images.githubusercontent.com/1098257/35159393-c5056c04-fd42-11e7-9abf-41d0fabf7067.png)
search for 'acts' returns 'not found'

Output for manage.py rebuild_index -v2 is
```
...
Indexing 3 profiles
  indexed 1 - 3 of 3 (worker PID: 6575).
...
```
Result for sqs.count() 
```
>>> from haystack.query import SearchQuerySet
>>> sqs = SearchQuerySet().all()
>>> sqs.count()
```
is 0

**Comment by jaywink** [comment] 2018-01-20 12:17
It seems these users are filtered out because of visibility. The queryset [is like this](https://github.com/jaywink/socialhome/blob/aadc8123672a943329b850bb646a2648e296f49b/socialhome/search/views.py#L61). As a recap:

* If authenticated and staff -> return all
* else if authenticated -> exclude SELF and LIMITED profiles
* else include only PUBLIC

The visibilities are as follows:

    PUBLIC = 0
    LIMITED = 1
    SITE = 2
    SELF = 3

So, all the `acts` usernames in your image seem to have a visibility of 3 (self) or 1 (limited), and thus unless the user you are searching with is staff member, will be excluded.

Does changing their visibility to public/site and saving the profile re-index it and make the profile come up in search? For me locally this seems to work ok.

Note, our support for LIMITED visibility is not in yet, so that is why they are always excluded currently.

**Comment by autogestion** [comment] 2018-01-23 13:43
yes, changing visibility leads profile to come up in search

**Comment by jaywink** [comment] 2018-01-25 17:54
Great! Closing as "works as intended".

**Closed by jaywink** 2018-01-25 17:54 UTC
Labels: needs info
